### ISSUE TITLE
Pressing space after making a selection.

### ISSUE THREAD

**Issue by prakharsingh** [ericgio/react-bootstrap-typeahead#118]
After making a selection if space is pressed onChange event is fired with an empty array however, if any other key is pressed then it works fine and only onInputChange is fired.

**Comment by ericgio** [comment]
That doesn't sound correct, and I don't repro that behavior on the example. Any text change (space or chars) while there is a selection will clear the selection, thus triggering the `onChange` event. The `onInputChange` event will also be triggered since the input value has changed.

Feel free to reopen with additional context or explanation.
