### ISSUE TITLE
Cannot read property 'label' of null on 1.0.0.beta2 

### ISSUE THREAD

**Issue by michalzubkowicz** [ericgio/react-bootstrap-typeahead#121]
When someone's enter first letter which is not on an options list there is a error:
Cannot read property 'label' of null.

It doesn't happen on demos pages because demos always have all letters.

**Comment by ericgio** [comment]
Can you please provide repro steps?

**Comment by cephirothdy2j** [comment]
I'm seeing it too. Screenshot attached.

My component has one selection (`['Content-Type']`) and allowNew is `true`. Deleting a character in the middle of the string triggers the error. This happens regardless of whether `onChange` or `onInputChange` methods are attached to the component.
<img width="942" alt="screen shot 2016-12-15 at 11 38 34 am" src="https://cloud.githubusercontent.com/assets/881769/21232932/6578cbf4-c2bb-11e6-97a9-5a5d60001be0.png">

**Comment by cephirothdy2j** [comment]
A little more info ...

- The error can also be reproduced by adding a character to the end of the current input (assuming doing so does not create a string that matches at least one of your options)
- Deleting a character at the end of the string does NOT produce the error; assuming this is because the string then matches at least one of the component's `options`
- If you first make an edit to the input that does not trigger the error, any edits made to the input after that point that would normally trigger the error no longer trigger the error

**Comment by ericgio** [comment]
Thanks for the detailed info, I'll take a look.

**Comment by ericgio** [comment]
I can repro, thanks.

**Comment by ericgio** [comment]
Fixed `v1.0.0-beta3`

**Comment by cephirothdy2j** [comment]
Thanks!

Also, as an aside, I started looking into fixing the issue myself but didn't see any instructions on running the project or contributing and I gave up after running into some webpack issues. When you have time, it would be helpful if you could provide those instructions to make it easier for the community to help maintain this project. 🙂

**Comment by ericgio** [comment]
@cephirothdy2j: good feedback, thanks. I'll add some better instructions around installing the project and contributing. Beyond the standard `git clone` & `npm install`, what kind of instructions would have been helpful? Also, what were the webpack errors?

**Comment by cephirothdy2j** [comment]
The webpack issues I ran into were specific to my setup, as I was attempting to `npm link` my local copy of the the typeahead component in my project.

One thing that would be great in your repo would be a webpack dev server so that we could run the example from a command and have the module rebuild and refresh the page whenever a file changes.
