### ISSUE TITLE
When you select an option first time in input it shows ID, on second selection it shows label

### ISSUE THREAD

**Issue by michalzubkowicz** [ericgio/react-bootstrap-typeahead#123]
It should be configurable (what to show in input field ID or Label) and consistent. 

It occurs only when you have controllable input.

**Comment by ericgio** [comment]
Can you please add some code examples? The descriptions are a little vague... I appreciate the bug reports, though.

**Comment by michalzubkowicz** [comment]
Ok, I didn't know what you would need. 

There are my options

```
let options = [
            {id: 'aaaa', label: 'bbb'},
            {id: '2', label: '222'}
        ]
```

and JSX:

```
<Typeahead
   options={options}</Typeahead
```

If you push letter for example "x" you'll see that error.

**Comment by ericgio** [comment]
Is this your own code or are you modifying the example?

**Comment by michalzubkowicz** [comment]
Ok. I'll prepare test repo.

**Comment by ericgio** [comment]
Note that modifying the example to use these options will trigger a bug, since the example makes certain assumptions and has the `labelKey` hard-coded. I can't find anything wrong with the component itself based on your information, though.

**Comment by ericgio** [comment]
@michalzubkowicz: please reopen when you have repro steps outside of the example.

**Comment by michalzubkowicz** [comment]
I've prepared repo for this.
https://bitbucket.org/michal_zubkowicz/typeahead-test-case-123

please click in input, select value, and then again click in input and again select value. 
Input value will be once ID and once Label

**Comment by ericgio** [comment]
This is a bug in your code. To be honest, I don't really understand the data conversion you're doing here, since it seems unnecessary.

- `selected` should be a subset of `options` or a custom option. `this.state.model.fieldvalue` doesn't correspond to anything.
- You're setting the `fieldValue` to be the `id` on [line 24](https://bitbucket.org/michal_zubkowicz/typeahead-test-case-123/src/a84436537dbb86e43391d4358cf9fd86774aefea/src/App.js?at=master&fileviewer=file-view-default#App.js-24), which appears to be why it displays the id

You would greatly simplify things by just doing something like:
```jsx
<Typeahead
  options={this.state.options}
  onChange={(v) => this.setState({selected: v})}
  allowNew={true}
  selected={this.state.selected}
/>
```

**Comment by michalzubkowicz** [comment]
Maybe example is too complicated. This conversion is necessary because i need for model to hold only label of value. I understand now that fieldvalue should be element selected in component. You are right - I need to pass value in another way to model because this way it confuses Typeahead. Thank you.

**Comment by hsetiawan** [comment]
sfssfssdsdf
