### ISSUE TITLE
List display doesn't work when rendering from server (React + Redux + Router).

### ISSUE THREAD

**Issue by ing-fco-rguez** [ericgio/react-bootstrap-typeahead#129]
Hi, I'm in that part of the development of a React App when a server side rendering is needed (°~°)

I'm having a hard time making your component work for me again, even if I set the options manually, the dropdown list doesn't display (u_u)

¿Have you tried this out?, ¿do you have any suggestions?

Thank you very much in advance.

**Comment by ericgio** [comment]
I'm not too familiar with server-side React, so I'm afraid I won't be of much help. My sense is that components should work fine either way, it's just a matter of hooking them up properly once they're rendered in the client. Can you please post the question on StackOverflow with some code examples? If it turns out that there's actually a bug, please re-open this issue with more detail. Thanks.
