### ISSUE TITLE
Event for pagination click?

### ISSUE THREAD

**Issue by acroyear** [ericgio/react-bootstrap-typeahead#143]
We want to implement paging at the *server*/api level - only ask for 50 results at a time and only the next 50 if the user requests it, rather than loading ALL the results into the client and having the UI filter them. There are just too many (in some cases, thousands) which puts a huge load on the server/db, network, and UI across the board.

All of my attempts to implement such a feature, with the component as it is, have been unsuccessful often resulting in loops where it keeps asking for the same page of data over and over again.

So can you add an event on clicking the 'load next page' item (and an property to show it even if the current results set is equal to a multiple of a page of data), or would you be open to a pull-req that provided such a feature?

**Comment by ericgio** [comment]
Sounds like a reasonable request to me. I can look into it or if you have some code that you can put up as a PR, that might help with the conversation. Your use case sounds specific to loading data asynchronously, so my gut feeling is that this functionality would be exposed via `AsyncTypeahead`/`asyncContainer` rather than the main `Typeahead` component, which is synchronous. Thoughts?

**Comment by ericgio** [comment]
This was actually pretty trivial. Added an `onPaginate` prop in v1.1.0, which should give you what you need. Exposed in both the main `Typeahead` and `AsyncTypeahead` components.
