### ISSUE TITLE
Remove CSS from project and include it in docs

### ISSUE THREAD

**Issue by thijskramer** [ericgio/react-bootstrap-typeahead#15]
Currently this package depends on external configurations (for example the appearance of `style-loader` when using webpack) to include the stylesheets. 
I think the CSS shouldn't be included in this package, but instead should be mentioned in the docs, as a suggestion. Therefore it wouldn't be neccessary to override the included styles.
 
What is your opinion about this?

**Comment by ericgio** [comment]
Thanks for raising this issue @thijskramer. I've gotten a few comments about this; can you describe in a bit more detail why you don't think requiring the use of `style-loader` is acceptable? The problem is that without the CSS, the experience feels pretty broken. I guess I could break out the CSS and allow people to require the CSS however they want (or not at all), but it seems that bundling everything together is a neater way to provide a consistent experience.

**Comment by winstonewert** [comment]
Including the css breaks my environment, because I run my code in a plain node environment (for tests and server side implementation) so the style loading doesn't work.

See also discussion here: http://stackoverflow.com/questions/30347722

I think importing css like this makes too many assumptions about how the application using the module will handle its css needs.

**Comment by ericgio** [comment]
The CSS has been broken out as of v0.5.0, and the documentation now mentions this. You can include the CSS however you see fit.
