### ISSUE TITLE
Passing ref down the tree to children breaks getInstance()

### ISSUE THREAD

**Issue by Tauka** [ericgio/react-bootstrap-typeahead#151]
When I pass `Typeahead` ref down the tree, children seem to receive, but not able to call getInstance() on it.

Here is my code:

```javascript
componentWillReceiveProps(nextProps) {
		console.log(nextProps.typeahead);
	        if (nextProps.typeahead != null) {
		 	nextProps.typeahead.getInstance().clear();
	         }
	}
```

Calling `console.log(nextProps.typeahead)` alone works fine.
![image](https://cloud.githubusercontent.com/assets/15087247/23346524/188a04cc-fcc5-11e6-835c-174a6eea92da.png)

 But when I try to call `getInstance().clear()` on it, it returns error:
![image](https://cloud.githubusercontent.com/assets/15087247/23346510/ffd0a36e-fcc4-11e6-83f5-3233aee20a19.png)

**Comment by ericgio** [comment]
I'm not sure what the root cause of the error is, but there's almost certainly a better way to do what you're trying to do. Passing refs down the tree is not a recommended React pattern. Either way, this sounds like a problem with your code rather than the component. As mentioned in the [contribution guidelines](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/CONTRIBUTING.md), please try to keep the issue tracker limited to bugs and feature requests. Questions like this are more appropriate for StackOverflow and similar forums, since I don't have time to individually help everyone with questions. Thanks for understanding.

**Comment by Tauka** [comment]
@ericgio So you were not able to reproduce it? Anyway, thank you for spending your time.

**Comment by Tauka** [comment]
@ericgio By the way, is there any other way to programmatically clear the input from within a child?

**Comment by ericgio** [comment]
@Tauka: If you want to post your question on stack overflow with additional code context and maybe a jsfiddle repro case, I can try to help you out.
