### ISSUE TITLE
Allow null filterBy in async

### ISSUE THREAD

**Issue by web2wire** [ericgio/react-bootstrap-typeahead#160]
I am using a typeahead with async data which is refreshed on each keypress via onSearch. As such all the filtering is done on the back end only valid data is returned. So I do not need any filtering done by this component. However as it stands I have to create a function which does nothing.

It would be useful to support null for filterBy which bypasses this functionality altogether. As an additional data point it's not really clear what filterBy should return. I have assumed it's true for a match, which seems to work, but it would be helpful is the docs made this clear.

**Comment by ericgio** [comment]
`filterBy` is optional, you don't need to set the prop.

**Comment by ericgio** [comment]
Also closing this out as a non-issue, but go ahead and re-open with more information if you feel like I'm misunderstanding your problem.

**Comment by georgiosd** [comment]
Hey @ericgio I am seeing this also.

Basically, the server filters the results and typeahead should be instructed to NOT filter the results at all. It seems that by default it will filter them based on the label. Thus, it filtered out some valid results (because the search I do on the server is on more than one fields).

Does that make sense? I got around it by doing `labelKey='name' filterBy={() => true}` but it seems more appropriate to set the filter (or labelKey) to null.

**Comment by ywang04** [comment]
@ericgio just one quick question here regarding filterBy. I am creating a component which supports both sync and async search.
I just want to keep the filterBy in the component itself instead of asking dev to explicitly pass the filterBy prop when they want to use async search. However, in the component itself If I passing {() => true} to filterBy, which will break the sync search.  Is there way to avoid this issue? Below are my codes:
```

   <TypeaheadComponent
          id={id}
          renderMenu={renderMenu}
          options={options}
          paginate={false}
          maxResults={maxResults}
          labelKey={labelKey}
          onSearch={handleSearch}
          isLoading={isLoading}
           filterBy={() => true}  
// TypeaheadComponent supports both sync and async search but if we put the call back which returns true here, sync search is not working. 
          {...props}
        />
```
