### ISSUE TITLE
Feature Request: Enter key behavior

### ISSUE THREAD

**Issue by rockymeza** [ericgio/react-bootstrap-typeahead#173]
I wanted to ask if the following enter key behavior would be something that you would consider accepting, before I try to add it in a PR.

**State:** an option is highlighted in the menu.
**Current behavior:** select highlighted item
(no change)

**State:** user has typed a search, there are search results
**Current behavior:** nothing
**New behavior:** selects first result

**State:** user has typed a search, there are no search results (allowNew=false)
**Current behavior:** nothing
(no change)

**State:** user has typed a search, there are no search results (allowNew=true)
**Current behavior:** nothing
**New behavior:** creates new selection

**State:** user has not typed a search
**Current behavior:** event.preventDefault()
**New behavior:** allow submitting the form

Thanks!

**Comment by ericgio** [comment]
> State: user has not typed a search
> Current behavior: event.preventDefault()
> New behavior: allow submitting the form

This should have been addressed with #135. You can set `submitFormOnEnter` to enable the behavior.

> State: user has typed a search, there are search results
> Current behavior: nothing
> New behavior: selects first result
> 
> State: user has typed a search, there are no search results (allowNew=true)
> Current behavior: nothing
> New behavior: creates new selection

These both seem to address the same behavior, which is auto-highlighting the first (or only) option. This issue is currently being tracked in #77. I've looked into adding support for this and as I recall, it wasn't as easy as it seemed at first glance. #136 tried to add it but only addresses adding the item and not auto-highlighting (which is the trickier piece). If you'd like to take a stab at it, by all means go ahead.

**Comment by ericgio** [comment]
Closing, since these issues have either been addressed or are already being tracked.

**Comment by rockymeza** [comment]
thanks for the quick response! Thanks for pointing out `submitFormOnEnter` and I'll take a look at #77 and see if I can knock it out.
