### ISSUE TITLE
Show allow New for all selections 

### ISSUE THREAD

**Issue by kamarajuPrathi** [ericgio/react-bootstrap-typeahead#176]
Currently if i have a match recieved from service during type  a head , it removes the new item li
.

**Comment by ericgio** [comment]
The new selection menu item goes away when there's an exact match. I'm not sure why you'd want to display it in that case.

**Comment by kamarajuPrathi** [comment]
One of our requirement is that , Can you make it configurable ?
and One more item is can i add custom style to the new item ?

**Comment by ericgio** [comment]
Seems like a pretty specific use case, and you haven't made a case for why it's important.

As far as styling the item, you can create a custom menu component and pass it to `renderMenu`. That will allow you to style the new item however you want.

**Comment by kamarajuPrathi** [comment]
ok , the other issue if renderMenuItem is when i search for something it just highlight as we get by default.

**Comment by ericgio** [comment]
I don't understand your question/comment.

**Comment by kamarajuPrathi** [comment]
<img width="356" alt="screen shot 2017-04-26 at 3 57 02 pm" src="https://cloud.githubusercontent.com/assets/25597219/25456618/0a494178-2a99-11e7-8bd0-b99e4a835ae7.png">
<img width="416" alt="screen shot 2017-04-26 at 3 56 50 pm" src="https://cloud.githubusercontent.com/assets/25597219/25456619/0a4a9d5c-2a99-11e7-9abf-c45cf7aeef75.png">

Do you see in image one it doesnt highlight the searchedText vs secondexample it highlights the serachedtext in the results

**Comment by ericgio** [comment]
Correct. `renderMenuItem` overrides the default highlighting feature. You'll need to add this back in yourself, using something like [`react-highlighter`](https://www.npmjs.com/package/react-highlighter).

**Comment by kamarajuPrathi** [comment]
Ok thankyou

**Comment by csuich2** [comment]
@ericgio I've hit this same issue and I can elaborate on our use case. We're using the typeahead to look up options for a filtering mechanism (like many e-commerce sites do for filtering). In addition to letting users pick specific results, we're also leveraging the 'Add New' as more of a generic search, where they can filter by all options that match against a string. However, if I wanted to match against a string where there is an existing specific result, the 'Add New' option disappears.

I totally get that this is a bit of a weird use case since this isn't exactly what your typeahead was designed for, but I think in our case, it is a great user experience. I wouldn't mind doing something a little hacky, but as of now, the only option I see for us is to monkeypatch addCustomOption to get rid of the exactMatchFound check.

If I were to make a PR that adds an option for this, would you be interested in entertaining it? Or are you opposed to this functionality? If so, I'll proceed with monkeypatching.

**Comment by ericgio** [comment]
@csuich2: Just so I understand, you're saying that you want to use the custom option to allow users to broadly filter items by the given string, but this isn't possible when there's an exact match, correct?

If so, I don't know that I have a great answer for you. What you're asking for seems like a reasonable experience, but also somewhat out of scope for the component since it's primarily intended for searching/filtering predefined data sets and not as a universal search box. It's also not clear that there's an easy or obvious way to make the API more flexible to allow this without feeling like a very one-off solution.

If you feel like exploring a bit and suggesting some possible solutions, please feel free, though I can't guarantee I'll want to merge a PR.

**Comment by csuich2** [comment]
I came up with another use case that might make this sound more appealing:

Since you can render custom menu items, I may have multiple menu items that are exact matches on the label key, but have different metadata which is displayed via my custom menu items. I may also allow users to add __additional__ menu items that are exact matches to the label key, but will end up with different metadata and are therefore different menu items.

**Comment by ericgio** [comment]
As of 3.2.0, `allowNew` accepts a callback to determine whether or not to add the custom option. Thanks to @csuich2 for the PR on that.
