### ISSUE TITLE
React 15 warning about controlled inputs

### ISSUE THREAD

**Issue by ericgio** [ericgio/react-bootstrap-typeahead#21]
"TypeaheadInput is changing a uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components"

**Comment by letthewookiewin** [comment]
The input element's value property need to be set to empty string, not undefined. _getHintText() and _getInputValue() are two places where undefined can be returned instead of a string.

See also: https://www.garysieling.com/blog/fixing-react-error-input-changing-controlled-input-type-text-uncontrolled

**Comment by ericgio** [comment]
Nice, thanks for the tip. Fixed in v0.5.3
