### ISSUE TITLE
ignorePunctuation

### ISSUE THREAD

**Issue by derwaldgeist** [ericgio/react-bootstrap-typeahead#230]
I am using your great package to do a suggest search on OpenStreetMap data. Here, it is quite common that the results contain additional information. For instance, instead of

`Berlin`

you would return

`Berlin (Germany)`

In the default setup, the user is forced to type the brackets. Otherwise, the result would be filtered out. This is unintuitive.

I've seen that there is an option to add a custom filter. But I think filtering punctuation (i.e. everything except letters and numbers) is quite a common usecase. So it would be great if there was an option for this. IMHO, this should even be the default setting.

**Comment by ericgio** [comment]
I'll leave this open for discussion, but it's unlikely I'll add this in the near future. I actually don't think it's all that common of a use case and as you point out, there are already ways to work around it.

**Comment by aikidoshi** [comment]
I'm having a similar problem, my users want to search using surname, firstname because it is common practice e.g., Ni, Emma
Problem is that the comma is processed correctly and the results are loaded into the options array in State but are then NOT displayed by the AsyncTypeAhead component. Same if I use a space instead of a comma.
This is surprisingly a big issue apparently, we have a 100 cheungs and even more nguyens.
Please advise.
Regards,
Steve (aikidoshi) Bond

**Comment by ericgio** [comment]
@aikidoshi: As noted above, [`filterBy`](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Filtering.md#filterby-arraystring--function) allows you to write a custom filter for your data.

**Comment by ericgio** [comment]
Unless I'm missing something or there's a use case I'm not aware of, I believe the `filterBy` prop addresses this issue. Closing for now.
