### ISSUE TITLE
Option List display inconsistency

### ISSUE THREAD

**Issue by solace** [ericgio/react-bootstrap-typeahead#235]
Hi,

Got a question about how the list of options is rendered.

When you start typing, it filters out the options to the ones that match.
When you select an option, clicking in the field only shows the one remaining option that was selected in the list in bold.
If you reload the page, the option is still populated, but now the full option list is displayed (presumably because it hasn't detected anything has been typed to trigger the filtering).

This behaviour makes sense, but I'm wondering if it's possible, once an option has been selected, for the full list of options to be displayed again.

**Comment by ericgio** [comment]
> If you reload the page, the option is still populated, but now the full option list is displayed

I don't know how you're seeing this behavior, since the option should clear on a page reload.

> I'm wondering if it's possible, once an option has been selected, for the full list of options to be displayed again

Sure, you can pass a callback to the [`filterBy`](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Filtering.md#callback-filterbyoption-text) prop and have it filter options however you want.
