### ISSUE TITLE
Backspace after selection triggers onChange

### ISSUE THREAD

**Issue by thefoolofemmaus** [ericgio/react-bootstrap-typeahead#250]
### Version
2.0.0-alpha.4

### Steps to reproduce
Using AsyncTypeahead 
1. Type text to produce suggestions
2. Select a suggestion
3. Hit backspace to remove the last character from the selection

### Expected Behavior
prop onSearch is fired.

### Actual Behavior
prop onChange is fired with a blank value.

**Comment by ericgio** [comment]
Does `onSearch` not also get fired? Note that it's expected for `onChange` to be triggered, since deleting a character removes the selection.

**Comment by ericgio** [comment]
I don't repro the issue you describe using [the example](http://ericgio.github.io/react-bootstrap-typeahead/2.0/#asynchronous-searching). When I hit backspace, a new query is fired as you'd expect. As noted above, it's expected for `onChange` to be fired, since the selection changed. I'm going to consider this issue closed, but feel free to re-open with more info if I'm not understanding something.
