### ISSUE TITLE
Bind Id and Label to typeahead control

### ISSUE THREAD

**Issue by jani937** [ericgio/react-bootstrap-typeahead#253]
Hi,
I have requirement where i would need to load all employees into a drop down list  and show employee name as display item and employee id as selected list item value.

Now i will have to filter employee table data by selected employee id. Below is my source looks like.
source = [{id: 1, name: 'abc'},
                {id:2, name:'xyz'},
                {id3, name: 'mno'}]

Can you please let me know how can i bind above source to typeahead and set id as source.id and display name as source.name.

Appreciated your support in advance. 
Thanks,

**Comment by ericgio** [comment]
Hi, questions like this are more appropriate for a forum like StackOverflow since your question will remain open and potentially help others facing the same issue. Posting there also helps me keep the issues queue manageable and limited to bugs and feature requests. Feel free to post a link to your SO question on this thread and I'd be happy to try and help.

https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead

Thanks.
