### ISSUE TITLE
Warning: Failed prop type: The prop `isLoading` is marked as required in `Container`, but its value is `undefined`.

### ISSUE THREAD

**Issue by hyzhak** [ericgio/react-bootstrap-typeahead#262]
### Version

`v2.0.0-rc.4`

### Steps to reproduce

Create an instance of `AsyncTypeahead`.

### Expected Behavior

`isLoading` is required property in `Typeahead` so `Container` should pass it here https://github.com/ericgio/react-bootstrap-typeahead/blob/2.0/src/containers/asyncContainer.js#L59.

### Actual Behavior

I'm getting warring when I'm using async typeahead:

> Warning: Failed prop type: The prop `isLoading` is marked as required in `Container`, but its value is `undefined`.

**Comment by ericgio** [comment]
This is expected. v2.0.0-rc.1 introduced [a breaking change](https://github.com/ericgio/react-bootstrap-typeahead/releases/tag/v2.0.0-rc.1) to `AsyncTypeahead` requiring the use of `isLoading` to track request state. So you need to pass that value in.

You're seeing the warning now because I accidentally left the default value in, but removed it in v2.0.0-rc.3
