### ISSUE TITLE
how to turn off autocorrect when using on mobile

### ISSUE THREAD

**Issue by vominhtam** [ericgio/react-bootstrap-typeahead#264]
Hi all,

I have issue when using react-bootstrap-typeahead on mobile. I want to turn off autocorrect of input but i don't know how to do it.

please help me. 
thank all so much.

**Comment by ericgio** [comment]
Hi, questions like this are more appropriate for a forum like StackOverflow since your question will remain open and potentially help others facing the same issue. Posting there also helps me keep the issues queue manageable and limited to bugs and feature requests. Feel free to post a link to your SO question on this thread and I'd be happy to try and help.

https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead

Thanks
