### ISSUE TITLE
Allow input customization

### ISSUE THREAD

**Issue by ericgio** [ericgio/react-bootstrap-typeahead#316]
This would address #72 and #308. No current timeline, but likely involves breaking changes or at least significant internal refactoring, so probably not before v3.0

**Comment by ArchSerpo** [comment]
Has there been any progress on this?

**Comment by ericgio** [comment]
There has been some progress, but nothing exposed in the public API yet, unfortunately.

**Comment by arichter83** [comment]
In regards to #308 I tried to add a separate `<textarea>` which behaves like the `<input>` and hide that one, but it turns out very hacky. An obvious problem is all the event handling towards the menu, and especially the `onKeyDown` for up/down selecting inside the menu. Will this ticket be a better solution and can I see the work in progress?

**Comment by ericgio** [comment]
@arichter83: Yes, the solution I have in mind would aim to provide an API for customizing the input piece of the typeahead. Unfortunately I don't have a timeline for when that might be completed. As you note, the input is a much more complicated piece of the overall component than the menu, so I've been trying to find ways to allow full flexibility while making that complexity transparent.

**Comment by ericgio** [comment]
A `renderInput` hook was added in the v4.0 pre-release. Docs and example added as well.
