### ISSUE TITLE
submitFormOnEnter does not work

### ISSUE THREAD

**Issue by SergeyShablenko** [ericgio/react-bootstrap-typeahead#342]
Why you removed submitFormOnEnter functionality? Please provide some workaround

### Version

3.0.3

### Steps to reproduce

press ENTER

### Expected Behavior

form is submited

### Actual Behavior

form is not submited

**Comment by ericgio** [comment]
@SergeyShablenko: Please elaborate on your use case. Your description is neither helpful nor accurate, since it is indeed possible to submit the form. Also, the prop was removed in v3.1.0 so if you're on v3.0.3 the behavior you're seeing is not due to the removal.

Some background on the `submitFormOnEnter` prop: As originally written, the component prevented form submission under *any* circumstance while focused, so the prop was introduced to allow developers to control the behavior. v2.0 [updated the behavior](https://github.com/ericgio/react-bootstrap-typeahead/commit/02c8a703b88bb204b5348477a5d13f2eca9cc723) to only prevent form submission when the menu is open. This made the typeahead's behavior more consistent with a standard `select` element, for example. Given the more reasonable default behavior, I can't see a convincing reason to retain `submitFormOnEnter`.

**Comment by ericgio** [comment]
Here's a way to override the behavior:

```jsx
<Typeahead
  onKeyDown={(e) => {
    if (e.keyCode === 13) {
      // Submit the form
    }
  }}
  ...
/>
```

**Comment by ericgio** [comment]
@SergeyShablenko: I'm going to consider this issue closed unless you feel you have a compelling argument.
