### ISSUE TITLE
AsyncTypeahead not showing results

### ISSUE THREAD

**Issue by chkrishna2001** [ericgio/react-bootstrap-typeahead#343]
### Steps to reproduce 
I am using below code, it works sometimes, sometime it don't show results but the network calls shows data
```jsx
<AsyncTypeahead
  isLoading={this.props.userStore.IsUserTypeaheadLoading}
  onSearch={(query)=>{ this.props.userStore.SearchUsers(query); }}
  options={this.props.userStore.Users}
  onChange={(selected)=> this.props.userStore.UpdateTypeAHeadSelection(selected,"user") }
  labelKey="UserFullName"
/>
```
My response looks like below
```
[
  {"UserId":"fdfd","UserFullName":"ewe rerre"},
  {"UserId":"asdasd","UserFullName":"ghtrbfgb gf"},
  {"UserId":"uy","UserFullName":"nvhghgn"},
  {"UserId":"ytytty","UserFullName":"ghjhfhfh"}
]
```

### Expected Behavior
It should always show results
### Actual Behavior
Sometimes it shows results but sometimes it own't

**Comment by ericgio** [comment]
Hi, it looks like you're asking for help with your code. Questions like this are more appropriate for a forum like StackOverflow since your question will remain open and potentially help others facing the same issue. Posting there also helps me keep the issues queue manageable and limited to bugs and feature requests. Thanks.

https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead

If you're actually trying to file a bug, please provide a minimal repro case and re-open the issue.

**Comment by chkrishna2001** [comment]
Hi Eric,

   It seems to be a bug to me, without filterBy to all the fields the data is getting filtered and returning zero results which doesn’t seem to be a correct behavior. 

Thank you 
Krishna Chirravuri

**Comment by ericgio** [comment]
If you feel it's a bug, please provide either a minimal repro case that doesn't rely on external libs, or very specific steps to reproduce the issue using [the examples](http://ericgio.github.io/react-bootstrap-typeahead/). Thanks.
