### ISSUE TITLE
Add multiple labelkeys

### ISSUE THREAD

**Issue by nat009** [ericgio/react-bootstrap-typeahead#353]
Is there a way we can add multiple labelkeys
for eg this is what i have. In my search dropdown I'd like to have the same values as the filterby.  Even though i can filterby Company', 'Company2', 'value', it gets confusing as i have only company in my labelKey
```jsx
<Typeahead
  labelKey='company'
  multiple
  clearButton
  filterBy={['Company', 'Company2', 'value']}
  options={[
    { id: 123, Company: 'Microsoft', Company2: 'test', value: '1000' },
    { id: 245, Company: 'Google', Company2: 'Alphabet', value: '2000000' },
    { id: 345, Company: 'Google', Company2: 'abc', value: '400000000' },
    { id: 456, Company: 'Amamzon', Company2: 'abc', value: '10000000' },
    { id: 678, Company: 'Walmart', Company2: 'Flipkart', value: '2000000' },
    { id: 789, Company: 'Test123', Company2: 'Test', value: '80000000' }
  ]}
  selected={this.selected}
  onChange={this.handleSearchChange}
  placeholder='Search Deal'
/>
```

**Comment by ericgio** [comment]
There are a couple ways you can accomplish what you want. Take a look at the [rendering docs](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Rendering.md) for more detailed information.

1. You can [pass `labelKey` a function](http://ericgio.github.io/react-bootstrap-typeahead/#labelkey) to specify the label string you want:

```jsx
<Typeahead
  labelKey={option => `${option.Company} ${option.Company2}`}
  ...
/>
```

2. You can use the [`renderMenuItemChildren`](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Rendering.md#rendermenuitemchildrenoption-objectstring-props-object-index-number) prop for more control over how the information is displayed in the menu item:

```jsx
<Typeahead
  renderMenuItemChildren={(option, props) => (
    <div>
      <div>{option.Company} {option.Company2}</div>
      <small><strong>Value:</strong> {option.value}</small>
    </div>
  )}
  ...
/>
```
(See also [this example](http://ericgio.github.io/react-bootstrap-typeahead/#custom-filtering))

Hope that helps.

**Comment by nat009** [comment]
Thanks that helped. :)

**Comment by jspinella** [comment]
My situation is a little bit different. I am returning a list of results from an API based on a query. The list of items that are returned are all matches, but the typeahead only shows some because some are permutations of the search query itself (even though they are matches... it's a sort of fuzzy search). 

In this scenario, I don't need or want the typeahead to determine which of the items to show and not show. Is there a way to not set labelKey and just show all items in the array of options?

It seems like we wouldn't want the typeahead using CPU cycles to compare the list of results with the user's input when the API is doing that for us.

**Comment by ericgio** [comment]
@jspinella: I don't think `labelKey` applies in your case. You probably want to take a look at [`filterBy`](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Filtering.md#functionoption-objectstring-props-object) and pass a callback that disables filtering by always returning `true`.
