### ISSUE TITLE
How to add caret button on dropdown

### ISSUE THREAD

**Issue by shobhitnpm** [ericgio/react-bootstrap-typeahead#366]
Hi, I want to add caret button on this dropdown, please suggest.

**Comment by ericgio** [comment]
Hi, questions like this are more appropriate for a forum like [StackOverflow](https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead) since your question will remain open and potentially help others facing the same issue. Posting there also helps me keep the issues queue manageable and limited to bugs and feature requests. Feel free to post a link to your SO question on this thread and I'd be happy to try and help. Thanks.
