### ISSUE TITLE
Material UI Support

### ISSUE THREAD

**Issue by bugzpodder** [ericgio/react-bootstrap-typeahead#367]
I've been looking at typeaheads (react-select, downshift) styled using material-ui and haven't found one to my liking.
How feasible is it to style react-bootstrap-typeahead using material-ui css?
Is it just a matter of creating my own css and include it globally?
I haven't seen anything bootstrap specific in this code base.

**Comment by ericgio** [comment]
I would imagine it's doable, though I haven't tried it myself. This library is definitely intended to work with Bootstrap (v3 & v4), so you might need to jump through a few hoops to get it working and even then some things might not be possible with the current API. The single-select case should be pretty easy to do, but the multi-select version has a bunch of custom CSS you'd need to override, making that one harder. Off the top of my head, you'd need to do the following (single-select case):

- Omit the basic Bootstrap stylesheet and include MUI instead
- Add the appropriate MUI classnames for the `input` using `inputProps`
- Assuming you're currently using MUI React components, use the `renderMenu` prop to render the typeahead menu using MUI's `MenuItem` and `MenuList` components.
- Cross fingers?

I've been considering creating an abstract version of the component that has no opinion with regards to style, but haven't gotten around to building it.

**Comment by bugzpodder** [comment]
Thanks for the detailed feedback.  I really like this component and will take a look at this integration. I will post back if I make any progress.

**Comment by kamarajuPrathi** [comment]
@bugzpodder did you make any progress ?

**Comment by bugzpodder** [comment]
No

**Comment by ericgio** [comment]
Here's a sandbox with a basic example using material-ui to render the components. It's single-select only; you'd have to create your own multi-select component or apply Material styles to the one included in this package.

https://codesandbox.io/s/rbt-mui-example-h6d5n

**Comment by chriszirkel** [comment]
> Here's a sandbox with a basic example using material-ui to render the components. It's single-select only; you'd have to create your own multi-select component or apply Material styles to the one included in this package.
> 
> https://codesandbox.io/s/rbt-mui-example-h6d5n

This example seems not to work with the current implementation of MUI or RBT. In my case, the menu popup will be shown as transparent (opacity: 0) and wrong positioned due to missing reference element of TextField.

I'm fairly new to react. Do you have an example on how to use the renderInput function with MUI TextField regarding inputRef and referenceElementRef?

**Comment by ericgio** [comment]
> I guess the ref of TextField refers to the referenceElement and the inputRef to the actual input field. Is that correct?

Not quite. The `inputRef` argument passed to `renderInput` is a [callback ref](https://reactjs.org/docs/refs-and-the-dom.html#callback-refs) that must be attached to the underlying `<input>` node of whatever component you're using for your input. If you were using a plain `<input>`, you would pass it to the `ref` prop. In the case of `TextField`, the `inputRef` prop is exposed to let you pass a ref directly to the `<input>` node rather than the outer wrapper node.

On the other hand, `referenceElementRef` can be attached to any node you choose. That node becomes the reference node for [Popper](https://popper.js.org/) to position the menu. Often (but not always), `inputRef` and `referenceElementRef` can be attached to the same node, but you may sometimes want them to be different.

**Comment by ericgio** [comment]
As a concrete example, compare the single- and multi-select versions of the typeahead inputs.

In the [single-select version](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/src/components/TypeaheadInputSingle.js), both `inputRef` and `referenceElementRef` are passed to the same element. In the [multi-select version](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/src/components/TypeaheadInputMulti.js), `inputRef` is passed to the `<input>` while `referenceElementRef` is passed to the container element.
