### ISSUE TITLE
Add caret button(arrow button) on dropdown textbox

### ISSUE THREAD

**Issue by shobhitnpm** [ericgio/react-bootstrap-typeahead#368]
I want to add caret or arrow button on dropdown text box, like 

![32886112-a98e0006-cae5-11e7-8b56-dd1f3f471cf7](https://user-images.githubusercontent.com/31316434/43541151-4924655c-95e7-11e8-8fb2-05e6fe06384b.PNG)

please give some suggestions.

**Comment by ericgio** [comment]
Hi, questions like this are more appropriate for a forum like StackOverflow since your question will remain open and potentially help others facing the same issue. Posting there also helps me keep the issues queue manageable and limited to bugs and feature requests. Feel free to post a link to your SO question on this thread and I'd be happy to try and help.

https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead

Thanks

**Comment by beulahpt** [comment]
@shobhitnpm did you find solution for this?

**Comment by ericgio** [comment]
@beulahpt: Please have a look at this [combobox example](https://codesandbox.io/s/rbt-combobox-example-kkmyd) to see how you can customize the component.
