### ISSUE TITLE
Prompt Text not working For AsyncTypeahead Component

### ISSUE THREAD

**Issue by raman162** [ericgio/react-bootstrap-typeahead#378]
### Steps to reproduce

Create an async typeahead component with the `promptText` prop.

```jsx
<AsyncTypeahead
  {...this.state}
  labelKey="login"
  minLength={3}
  onSearch={this._handleSearch}
  promptText={'Type to begin searching'}
  placeholder="Search for a Github user..."
  renderMenuItemChildren={(option, props) => (
    <GithubMenuItem key={option.id} user={option} />
  )}
/>
```
### Expected Behavior

The prompt appears as soon as the user focuses their input.

### Actual Behavior

The prompt ~never displays~ only displays until the first request is made to the server.

**Comment by ericgio** [comment]
It's expected behavior for the menu not to display on focus if `minLength` > 0. If you want to display a prompt to the user on focus, there are a couple ways to do that:

1) Use the input's placeholder instead of the menu.
2) If you really want to prompt to be in the menu, set `minLength` to `0`. You can then check the query length in your `onSearch` function to prevent requests below a certain threshold.
