### ISSUE TITLE
Placeholder not showing correctly when inside a modal

### ISSUE THREAD

**Issue by YassienW** [ericgio/react-bootstrap-typeahead#423]
### Version

3.3.4, BS4

### Steps to reproduce

Create a Typeahead with `multiple` and `placeholder` inside a modal

### Expected Behavior

The placeholder should fully show once the modal is open, without having to focus on the field

### Actual Behavior

![selection_004](https://user-images.githubusercontent.com/11986226/52979541-c0170080-33de-11e9-9477-082e781b4e52.png)

The placeholder text is initially cut off, you have to focus on the field in order for the placeholder text to appear. This happens due to the fact that the width of the input element is initially set to 3px, which doesn't expand until after focus.

**Comment by ericgio** [comment]
Hmm, looks similar to #256, which should have been resolved. I'll take a look.

**Comment by ericgio** [comment]
@YassienW I'm unable to repro with either BS3 or 4. Can you please provide a sandbox reproducing the issue? Thanks.

**Comment by YassienW** [comment]
[Yessir](https://codesandbox.io/s/5x0x41o96k)

Note that it only happens the first time you open the modal.
My application dynamically removes the dom element and re-adds it on click for performance, which causes this to happen every time the modal is closed and reopened.

**Comment by ericgio** [comment]
Thanks for the sandbox link, however it doesn't appear to open a modal or use the typeahead. Can you  please double check that it's correct?

**Comment by YassienW** [comment]
That's odd, can you try it again please? Should be working now

**Comment by ericgio** [comment]
Thanks. It looks like you're relying on bootstrap.js rather than a React-based framework like [react-bootstrap](https://react-bootstrap.github.io/) or [reactstrap](https://reactstrap.github.io/). I think what's happening is that the typeahead is not being updated because bootstrap.js operates on the DOM and bypasses the normal React lifecycles. I don't think there's much I can do about that, unfortunately. If you're going to be using React, I would strongly advise you to use one of the frameworks I mentioned (or something similar).

**Comment by ericgio** [comment]
Here's an updated example using react-bootstrap: https://codesandbox.io/s/9lvk69vk5w

Works fine in this case.

**Comment by YassienW** [comment]
Yeah, i am using JQuery for the modals. I will be switching to reactstrap ASAP and letting you know if it fixes it. Thanks!

**Comment by YassienW** [comment]
Switching to reactstrap sorted this out. Thanks the help Eric.
