### ISSUE TITLE
Undefined line show up using Menu

### ISSUE THREAD

**Issue by hkarn** [ericgio/react-bootstrap-typeahead#450]
### Version
4.0.0-alpha.10

### Steps to reproduce

Component props
```jsx
renderMenu={(results, menuProps) => (
  <Menu {...menuProps}>
    {results.map((result, index) => (
      // typeof result.firstname !== 'undefined' ?
        <MenuItem key={index} option={result} position={index}>
          <div key={index} className="small m-0 p-0">
            <p className="m-0 p-0">{result.organisation}</p>
            <p className="m-0 p-0">{result.firstname + ' ' + result.lastname}</p>                   
          </div>
        </MenuItem> // : null
    ))}
  </Menu>
)}
```

### Expected Behavior

"undefined undefined" should not show in result set

### Actual Behavior

`<p className="m-0 p-0">{result.firstname + ' ' + result.lastname}</p>`
Can sometimes create a line 
undefined undefined on empty result, even if no empty item is in option set

**Comment by hkarn** [comment]
Doing it like this instead shows a blank instead
<p className="m-0 p-0">{result.firstname} {result.lastname}</p>

I think it is the line at bottom that can be clicked to show more results so probably not a bug afterall. 
But why is the line blank?

**Comment by ericgio** [comment]
Hi @hkarn, thanks for reporting this issue. I'm having trouble understanding what the actual problem is. The code you posted only shows the menu rendering code. If you're getting undefined values there, it means there's something going on with your data filtering, which is further upstream. Can you please post a more complete code example, or better yet, a working sandbox? Thanks.

**Comment by hkarn** [comment]
Here is the entire component. https://github.com/HisingeBussAB/reko-tour-booking-system/blob/feature-grouplists/front/src/screens/lists/list-groups.js

I don't think the issue is with the data, I think it happens when there are more results then maxResults and there seems to be an option inserted to show more options.

The line that shows undefined undefined doesn't select anything when clicked so it doesn't appear an option coming from the data set, what it does is extend the list of results and shows more options. 
In the second example the line is still there and can be clicked to show more results but totally blank and extremely narrow.

**Comment by ericgio** [comment]
Ah ok, I see what's happening. Yes, you're right, that is the pagination item being appended to the result set. You're using the `Menu` component, which doesn't automatically handle that item. You either need to handle it as a separate menu item or you can just omit it with `paginate={false}`.

Alternatively, you could use `renderMenuItemChildren` instead of `renderMenu` and the menu will handle pagination for you:

```jsx
<Typeahead
  ...
  renderMenuItemChildren={(result, props, index) => (
    <div key={index} className="small m-0 p-0">
      <p className="m-0 p-0">{result.organisation}</p>
      <p className="m-0 p-0">{result.firstname} {result.lastname}</p>                   
    </div>
  )}
/>
```

**Comment by ericgio** [comment]
@hkarn, I'll consider this issue closed for now. Feel free to provide more info if you feel I've missed something or didn't fully address your issue.
