### ISSUE TITLE
Change ui input

### ISSUE THREAD

**Issue by Angelk90** [ericgio/react-bootstrap-typeahead#458]
**Is your feature request related to a problem? Please describe.**

![](https://i.stack.imgur.com/oJ2ah.png)

I would like to be able to change the input field ui as follows, as seen in the image.

It would be possible to do such a thing.

**Comment by ericgio** [comment]
Hello, usage questions like this are more appropriate for a forum like StackOverflow since your question will remain open and potentially help others facing the same issue. Posting there also helps me keep the issues queue manageable and limited to bugs and feature requests. Thank you.

https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead
