### ISSUE TITLE
Why is bodyContainer deprecated?

### ISSUE THREAD

**Issue by kklok** [ericgio/react-bootstrap-typeahead#490]
Why is bodyContainer marked deprecated? I find this feature a life savior in case of overflow containers

**Comment by ericgio** [comment]
Hi @kklok, please note that the `bodyContainer` *prop* is deprecated, not the functionality. As the warning states, you should use `positionFixed` instead. This is because v4 of the component uses [popper.js](https://popper.js.org/) (via [react-popper](https://github.com/FezVrasta/react-popper)) to position the menu.

**Comment by kklok** [comment]
Got it, thank you
