### ISSUE TITLE
Problem with validations

### ISSUE THREAD

**Issue by guillept** [ericgio/react-bootstrap-typeahead#491]
### Steps to reproduce

Hey there. I am having some trouble with the Typeahead component. I have it inside a form and I am validating that form with Bootstrap's `was-validated ` class.

` <form onSubmit={this.handleSubmit} className={this.state.validation} noValidate>`

where `this.state.validation` is `needs-validation` or `was-validated`. 

The problem is that whenever I click the submit button, the Typeahead is marked automatically as `isValid` althought I haven't selected any valid option and there is no default value.

I have tried to manage the `isValid` and `isInvalid` props but haven't manage to solve this problem. I also saw this was discussed in issue !331 but didn't manage to solve my problem.

### Expected Behavior

I would excpet that this input was marked as invalid whenever there is not a valid option selected.

### Actual Behavior

![Captura de Pantalla 2019-10-04 a la(s) 17 23 06](https://user-images.githubusercontent.com/22205342/66244172-d7380380-e6cc-11e9-95d9-0b80fe46e99f.png)

**Comment by ericgio** [comment]
Hi @guillept, usage questions like this are more appropriate for a forum like StackOverflow since your question will remain open and potentially help others facing the same issue. Posting there also helps me keep the issues queue manageable and limited to bugs and feature requests. Thanks!

https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead
