### ISSUE TITLE
onChange to fire once `Enter` is hit

### ISSUE THREAD

**Issue by rostgoat** [ericgio/react-bootstrap-typeahead#492]
using `AsyncTypeahead` I want onChange to only start firing once `Enter` is pressed on the keyboard. is that possible?

Here is my flow right now:

1. I use `onKeyDown` to listen for the `Enter` event. 
2. Once enter is hit, I updated a state variable called `enterPressed`.
3. At this point, I would like to call `onChange` automatically but I do it manually (incorrectly I presume) by getting `componentDidUpdate` to call `this.onChange`. I do this to guarantee `this.state.enterPressed` will be true
4. This causes `onChange` to fire multiple times for some reason...where it should only be called once

The application is supposed to search for some area on a map and show it's markers after.

```
class Search extends Component {
  state = {
    isLoading: false,
    searchTerm: "",
    areas: areas,
    enterPressed: false
  };

  handleSubmit = e => {
    this.props.handleSubmit(e);
  };

  handleSearch = e => {
    if (this.state.enterPressed) {
      this.setState({ searchTerm: e });
      this.props.onSearchedInputChange(this.state.searchTerm);
      this.props.handleSubmit(e);
      this.setState({
        enterPressed: false,
        isLoading: false
      });
    }
  };

  keyDown = e => {
    if (e.key === "Enter") {
      this.setState({
        enterPressed: true,
        isLoading: true
      });
    }
  };
  componentDidUpdate() {
    this.handleSearch();
  }

  render() {
    return (
      <div className="search">
        <Form onSubmit={this.handleSubmit}>
          <Form.Group controlId="searchForm" className="search-form">
            <InputGroup>
              <AsyncTypeahead
                isLoading={this.state.isLoading}
                labelKey="search"
                allowNew
                multiple
                newSelectionPrefix="Add a new item: "
                options={this.state.areas}
                placeholder="Type anything..."
                className="search-input"
                type="text"
                placeholder="Enter street or area..."
                value={this.state.searchTerm}
                name="search"
                onSearch={this.handleSearch}
                onKeyDown={this.keyDown}
              />
            </InputGroup>
          </Form.Group>
        </Form>
      </div>
    );
  }
}
```

**Comment by ericgio** [comment]
Hi @rostgoat, thanks for filing this issue. Usage questions like this are more appropriate for a forum like [StackOverflow](https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead) since your question will remain open and potentially help others facing the same problem. Posting there also helps me keep this issues queue manageable and limited to bugs and feature requests.

That said, you might be able to achieve the behavior you want with this component, but based on your description you may want to consider a different one entirely. A typeahead is generally meant to display results *as the user types*, so retrieving results on `enter` is a somewhat different use case. You could probably get by with a much simpler component.
