### ISSUE TITLE
AsyncTypeahead missing text in menuProps

### ISSUE THREAD

**Issue by daschi** [ericgio/react-bootstrap-typeahead#507]
Thank you for this package! I am not sure if I found a bug, or if I've setup my `AsyncTypeahead` incorrectly. I appreciate the support!

### Version

4.0.0-alpha.10

### Steps to reproduce

[Here's a CodePen that reproduces the bug](https://codepen.io/daschi/pen/YzPwdRj?editors=1011)

 I'm trying to render a custom menu that includes the `Highlighter` component, and I expected `menuProps` to have a `text` property that I could pass to the Highlighter search prop. However in my example, `menuProps.text` is `undefined`.

### Expected Behavior

I expect  the `text` property to be available in the `menuProps` provided by `renderMenu`. 

### Actual Behavior

When using `renderMenu` in the `AsyncTypeahead`, `menuProps.text` is `undefined`

**Comment by ericgio** [comment]
Hi @daschi, thanks for the report. It's not a bug, but it is a breaking change that I failed to document. The `renderMenu` hook now has three arguments:

```jsx
<Typeahead
  ...
  renderMenu={(results, menuProps, props) => (
    // Your menu rendering code here...
  )}
/>
```
The `text` value can now be found on `props` instead of `menuProps`. Sorry for the lack of documentation, I'll update the docs and the upgrade guide ASAP.

**Comment by daschi** [comment]
Thank you, got it working!
