### ISSUE TITLE
Options are not visible to select after clearing the input

### ISSUE THREAD

**Issue by robert-nash** [ericgio/react-bootstrap-typeahead#538]
### Version

4.2.0

### Steps to reproduce

https://codesandbox.io/s/cool-feistel-jviv1 [clearButton]
https://codesandbox.io/s/nostalgic-mendeleev-u4373 [Call clear method onFocus]

### Expected Behavior

I am not sure whether this is a bug or a feature request, but the behaviour seems strange to me. I would expect that after the Typeahead has been cleared and remains in focus, it would remain 'open' with all of the options shown to select.

### Actual Behavior

When clearButton is passed and you click on the clear button the input is cleared as expected. However, whilst the input remains focused, none of the available options are shown below the input (I believe this might be referred to as open). To see the options you have to click in the box again or start typing which then shows a filtered list of options.

I am not sure whether this behaviour is intended or not but for my use case it would be great if it was 'fixable' or if there was an option to customise the behaviour.

This behaviour becomes even more problematic when manually calling the clear method such as in the second sandbox where I want the input to be cleared when it receives focus.

**Comment by ericgio** [comment]
That is the expected behavior. For your second use case, you can call the `toggleMenu` method to reopen the menu after it's cleared:

```jsx
<Typeahead
  ...
  onFocus={event => {
    this._typeahead.clear();
    this._typeahead.toggleMenu();
  }}
  ref={typeahead => (this._typeahead = typeahead)}
/>
```
There's currently not a great API around this general use-case (other variations include keeping the menu open when removing selections in the multi-select case). I could possibly add an `onClear` hook (see #408) where you could call the `toggleMenu` method to keep the menu open. I'm not totally sure though, I'd have to think more about it.

**Comment by robert-nash** [comment]
Thank you, that would solve my problem.

**Comment by Valindo** [comment]
@ericgio could we close the issue then?
