### ISSUE TITLE
Move static styles to stylesheet 

### ISSUE THREAD

**Issue by mrdrogdrog** [ericgio/react-bootstrap-typeahead#548]
**Is your feature request related to a problem? Please describe.**
The css of every component is defined with inline style. This makes it very 
 difficult to override/modify the look or remove side effects in my app.

**Describe the solution you'd like**
Please extract the inline style rules into the scss file and use classes.

**How is this solution useful to others?**
This would make e.g. theming a lot easier.

**Comment by ericgio** [comment]
Hi @mrdrogdrog, thanks for filing this issue. Can you please be more specific about the problems you're encountering?

It's not true that every component has inline styles; only a few do, most notably the hint and multi-select `input` element. Most of the inline styles are functional in nature, though the two I mentioned add visual styles to normalize the appearance. The reason behind having inline styles in a few key places is to ensure basic functionality for the component even when the package CSS and Bootstrap CSS are not included.

**Comment by kersson** [comment]
Sorry if this is obvious, but given the inline style for multi-select `input`, how do we apply a custom style to this component? I'm specifically trying to configure the color of the search text. Thanks!

**Comment by ericgio** [comment]
@kersson: I'm not entirely sure what you're trying to do; posting your (S)CSS would be helpful. It sounds like you're trying to change the color of the input's text (not the placeholder color). I'm not sure what the `$input-color` variable refers to, is that a Bootstrap variable?

The multi-select input is actually a composite component, since `input` elements don't accept children. The `.form-control` classname is applied to a container element for styling, but the actual input is more or less unstyled. If you want to apply a specific color to the input, you'd need to use the proper CSS selector:

```
.rbt-input-main {
  color: $input-color;
}
```

The above will work for both single- and multi-select versions.

**Comment by kersson** [comment]
@ericgio: Apologies for the ambiguity. I only just started react and bootstrap programming in the last couple weeks. Yes, `$input-color` is a Bootstrap variable for forms: [scss/_variables.scss#L481](https://github.com/twbs/bootstrap/blob/v4.5.0/scss/_variables.scss#L481).

Your suggestion for using `.rbt-input-main` worked perfectly. Thanks so much!

**Comment by ericgio** [comment]
No response from OP, closing for now. @mrdrogdrog, I'm happy to reopen the issue if you can provide some more info about the problems you're facing.
