### ISSUE TITLE
bsSize props is ignored

### ISSUE THREAD

**Issue by shaneosullivan** [ericgio/react-bootstrap-typeahead#552]
### Version
5.0.0-rc.1

### Steps to reproduce

Setting the **bsSize** prop to **large** should change the UI to be larger, but it looks the same as **small**
See https://codesandbox.io/s/stoic-thunder-47md5?file=/src/index.js

### Expected Behavior
The UI should change size to be large

### Actual Behavior
The UI remains at the **small** size

Changing the **bsSize** prop has no effect

**Comment by ericgio** [comment]
Hey @shaneosullivan, thanks for filing this issue. `bsSize` was deprecated in [v4.2.0](https://github.com/ericgio/react-bootstrap-typeahead/releases/tag/v4.2.0) and removed in [v5.0.0-alpha.1](https://github.com/ericgio/react-bootstrap-typeahead/releases/tag/v5.0.0-alpha.1), so that is the expected behavior. I realize that I forgot to update the docs to reflect this change, however, so I apologize for the confusion.

**Comment by ericgio** [comment]
Docs updated on both master and 5.x branches.
