### ISSUE TITLE
Roadmap of features and bugfixes for 5.0.0 release

### ISSUE THREAD

**Issue by NathanTrost** [ericgio/react-bootstrap-typeahead#560]
My team is working on a project that currently uses 5.0.0-alpha.1, and I'm in the process of updating to 5.0.0-rc.3 just for the sake of keeping up with api changes in react-bootstrap-typeahead during it's move to the next major version.  There seems to be no indication as to when v5 might be released or what features or bugfixes will be targeted.  The milestone listed in this repo for v5 only lists the lifecycle methods update, which has now been completed.  Are there any more major changes for v5 in the pipeline that we can expect to account for?  Could you provide any insight as to the projected timeline for the v5 release?

**Comment by ericgio** [comment]
Hey @NathanTrost, thanks for the question. I can certainly understand the desire for some clarity around milestones and release timing.

It's unlikely that there will be any more major changes to v5 before it's released, so v5.0.0-rc.3 should be pretty stable barring any bugs I'm unaware of. I'd say timing for v5.0 release is "soon". There's probably no reason I couldn't release now, other than that I like to let the pre-release version bake a little and give developers the opportunity to report problems.

In general, I try to get the *current* major release (v4) to a stable place and fix any bugs that arise as quickly as possible. I typically haven't provided much guidance on timing of *future* major releases because I maintain this library in my spare time, which can fluctuate a lot. Given that, I'm unable to commit to specific timeframes. Similarly, while I keep a private list of ideas and planned features, I also generally haven't published a roadmap to avoid committing to features I might not be able to follow through on in a timely manner.

Hope that's helpful.

**Comment by NathanTrost** [comment]
Thanks @ericgio, that helps a lot!  I certainly understand the apprehension of commiting to anything in a roadmap, especially with this being privately maintained.  And I appreciate you keeping this out for a bit to prevent releasing unintended regressions on a major version.  I think this'll satisfy my team, we just needed some idea as to how much maintainence updating might require until v5 is fully released
