### ISSUE TITLE
Drag and drop reordering in multiselect

### ISSUE THREAD

**Issue by nathanielparke** [ericgio/react-bootstrap-typeahead#618]
**Is your feature request related to a problem? Please describe.**
For components that derive sort order form the typeahead there is no clean way for a user to re-order the list of items without deleting and re-entering the list.

**Describe the solution you'd like**
Would be nice to have draggable tokens that re-order the token list.

**How is this solution useful to others?**
This allows users to re-order the list which seems like a common enough use-case

**Describe alternatives you've considered**
Having a sort function external to the typeahead and inject the sorted list to the typeahead, treating it as a controlled component.

**Comment by ericgio** [comment]
Hi @nathanielparke, thanks for the feature request. Unfortunately, this isn't something I plan on implementing, since it would add significant complexity to the code for what I believe is a limited use case. The `renderInput` prop provides an API for developers to customize input rendering and behavior to their liking, so a custom implementation should be possible. In fact, the `TypeaheadInputMulti` component renders the tokens as children, so I think it should be reasonably easy to implement yourself.

**Comment by ericgio** [comment]
Duplicate of #80

**Comment by ericgio** [comment]
Here's a working example for reference: https://codesandbox.io/s/rbt-drag-drop-token-example-u43sf
