### ISSUE TITLE
Bootstrap 5 support

### ISSUE THREAD

**Issue by kimfucious** [ericgio/react-bootstrap-typeahead#621]
**Is your feature request related to a problem? Please describe.**
I recently strarted using Bootstrap 5 on a project, and the Typeahead CSS doesn't seem to properly render the clear button.

**Describe the solution you'd like**
I'd like to be able to add the `clearButton` prop on `Typeahead` and get the little grey X, instead of an unstyled button.

**How is this solution useful to others?**
Does your feature address a common use case? Does it provide a more generalized way to solve the type of problem you're encountering?
This would part of a way to futureproof this library to work with impendning versions of Bootstrap.

**Describe alternatives you've considered**
I haven't yet.

**Additional context**
Add any other context, sample code, or screenshots about the feature request here.
I love the ease of use of this library when compared with other packages!

**Comment by ericgio** [comment]
Hi @kimfucious, thanks for the feature request. I have plans to eventually support BS5 out of the box, though it's still in beta at the moment. Note that any styling issues like the one you're seeing are usually because the newer version of BS has updated a classname. In this case, they've changed the close button's classname from `close` to `btn-close`.

This and similar issues can be fixed by leveraging the typeahead's render functions to customize the components being rendered. For example, you can [use the typeahead's child render function](https://codesandbox.io/s/rbt-custom-aux-components-gn3kn) to render your own version of the clear button, adding the missing classname:

```jsx
import { ClearButton, Typeahead } from 'react-bootstrap-typeahead';

...

<Typeahead ... >
  {({ onClear, selected }) => (
    <div className="rbt-aux">
      {!!selected.length && <ClearButton className="btn-close" onClick={onClear} />}
    </div>
  )}
</Typeahead>
```

**Comment by kimfucious** [comment]
Thanks, @ericgio for the quick response.

It seems that I can make this work, with the insights you've provided, and I look forwrad to your future releases.

Keep up the awesome work!
