### ISSUE TITLE
How can set state use only a key of object ?

### ISSUE THREAD

**Issue by hoahiep506** [ericgio/react-bootstrap-typeahead#625]
```

<Typeahead
	clearButton
	id="basic-typeahead-multiple"
	multiple
	onChange={(id) => setClassId(id)}
	labelKey="name"
	valueKey="id"
	options={[
		{ id: 1, name: "10A" },
		{ id: 2, name: "10B" },
		{ id: 3, name: "10C" },
	]}
	placeholder="select class"
	selected={classId}
/>;
```

I want my state is classId = [ 1, 2, 3 ] but i got classId = [ { id: 1, name: "10A" }, { id: 2, name: "10B" }, { id: 3, name: "10C" } ]

How can we solve it ?

**Comment by ericgio** [comment]
Hi, @hoahiep506 questions like this are more appropriate for a forum like StackOverflow since your question will remain open and potentially help others facing the same issue. Posting there also helps me keep the issues queue manageable and limited to bugs and feature requests. Feel free to post a link to your SO question on this thread and I'd be happy to try and help. Thanks!

https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead
