### ISSUE TITLE
react-bootstrap-typeahead: How to get attribute value on “OnChange” , I am using Typeahead in table cell

### ISSUE THREAD

**Issue by johnmcclanes001** [ericgio/react-bootstrap-typeahead#651]
I am using react-bootstrap-typeahead in table row for invoice items.

my json is like [{record_id:1,value="value1"},{record_id:2,value="value2"}] on this basis I am creating bootstrap table. in table cell I am adding typeahead select box to change the value and update my json,

when I change the value I want to update my json array with latest value in related record. But as in onChange we only get selected array not an event object so, I am not able to find record id.

Please suggest me good solution.

**Comment by ericgio** [comment]
Hi @johnmcclanes001! Questions like this are more appropriate for a forum like StackOverflow since your question will remain open and potentially help others facing the same issue. Posting there also helps me keep the issues queue manageable and limited to bugs and feature requests. Feel free to post a link to your SO question on this thread and I'd be happy to try and help. Thanks.

https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead
