### ISSUE TITLE
Custom filterBy doesn't highlight when matching split words

### ISSUE THREAD

**Issue by Kzshii** [ericgio/react-bootstrap-typeahead#654]
Using filterBy to match split words instead of the exact match doesn't highlight the letters correctly

### Version

Latest: 5.1.4

### Steps to reproduce

https://codesandbox.io/s/peaceful-easley-je6gd

Search for Lorem and you will see `Lorem` highlighted, then search for `Lorem 4`, and the highlight will disappear 

![Captura de Tela 2021-07-01 às 21 50 38](https://user-images.githubusercontent.com/28403122/124204926-74001e80-dab6-11eb-803d-c64502589e1a.png)
![Captura de Tela 2021-07-01 às 21 50 46](https://user-images.githubusercontent.com/28403122/124204929-75314b80-dab6-11eb-9477-3046797125ff.png)

### Expected Behavior

Highlight `Lorem` and `4`

**Comment by ericgio** [comment]
Hey @Kzshii, thanks for filing this issue. The problem here isn't with the filtering, which is working correctly, but with the highlighting. The `Highlighter` component included with the library is fairly basic and doesn't handle fuzzy matches like what you're describing here. If you'd like to handle more advanced highlighting cases, I'd suggest replacing the built-in component with your own, using `renderMenu` or `renderMenuItemChildren` to replace the default rendering.
