### ISSUE TITLE
Prepopulate AsyncTypeAhead

### ISSUE THREAD

**Issue by Gc04346** [ericgio/react-bootstrap-typeahead#656]
Is there any way to prepopulate input text (not one of options item) using AsyncTypeahead?
When I use the "selected" prop, i get a warning saying that I whouldn't change a controlled component to be uncontrolled. Using defaultSelected clears the warning, but the prepopulation doesn't work.

**Comment by ericgio** [comment]
Hi @Gc04346 and thanks for the question! Please be sure to [read the documentation](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/API.md#props) to learn more about how the typeahead works.

I'm not sure what your needs are, but you can use either `selected` or `defaultSelected` to pre-populate the selected option in a [controlled](https://reactjs.org/docs/forms.html#controlled-components) or [uncontrolled](https://reactjs.org/docs/uncontrolled-components.html) manner, respectively. The warning you're seeing is due to the fact that you're using the prop inconsistently.

If you simply want to set the value of the input without actually setting the selection, you can use `defaultInputValue`. This prop only works in an uncontrolled way.

**Comment by mrpavk** [comment]
defaultInputValue isn't working on AsyncTypeAhead

**Comment by ericgio** [comment]
@mrpavk seems to work ok for me. Can you please specify what's not working for you? Thanks.
