### ISSUE TITLE
how to get rid of console error "controlled or uncontrolled element" ?

### ISSUE THREAD

**Issue by ahmadsaadkhan** [ericgio/react-bootstrap-typeahead#670]
Hello, I have implemented the react-bootstrap-typehead, it's working perfectly for both single and multiple but I am getting these console errors every time fields are rendered, how to remove these below code and console errors.

`<Typeahead
                id={label+'typeahead'}
                options={options}
                onChange={e => setData(e)}
                selected={name}
            />`

react_devtools_backend.js:4049 Warning: [react-bootstrap-typeahead] You are changing a controlled typeahead to be uncontrolled. Input elements should not switch from controlled to uncontrolled (or vice versa). Decide between using a controlled or uncontrolled element for the lifetime of the component. 
    at Typeahead (http://127.0.0.1:8000/js/app.js:56841:86)

**Comment by ericgio** [comment]
Hi @ahmadsaadkhan, thanks for the question. You're seeing this warning because you're initially passing a value to the typeahead (via the `selected` prop), and then at some later point you're passing a value of `undefined`. I'm not sure why this is happening since I can't see the rest of your code, but my guess is you're setting the value improperly somehow. You're using `setData` to set the selection, so I would expect something like `data` to be passed back into `selected`. Good luck!
