### ISSUE TITLE
Google Translate triggers error

### ISSUE THREAD

**Issue by javierguzman** [ericgio/react-bootstrap-typeahead#685]
Hello all,

I am using **react-bootstrap-typeahead** on my landing page and thanks to Sentry I have realized that my website crashes when someone using Google Chrome enables translation for my website. 

### Version

"^5.1.4

### Steps to reproduce
1. Visit www.kindoi.com using Google Chrome
2. Enable translation
3. Start typing in the search box

You will see the entire app crashing (Yes, I know I should have placed an error boundary!)

I will update the code in a few days, specifically, I want to place <html translate="no"> as a workaround, however, I will wait for a maintainer to respond before doing that. So someone can take a look at the real crash.

### Expected Behavior
No error happens

### Actual Behavior
From the stack error it seems the crash comes from this package:
```
The above error occurred in one of your React components:
    at Highlighter (webpack-internal:///../node_modules/react-bootstrap-typeahead/es/components/Highlighter.js:50:86)
    at a
    at eval (webpack-internal:///../node_modules/react-bootstrap-typeahead/es/components/MenuItem.js:19:21)
    at WrappedMenuItem (webpack-internal:///../node_modules/react-bootstrap-typeahead/es/behaviors/item.js:91:85)
    at div
    at Menu (webpack-internal:///../node_modules/react-bootstrap-typeahead/es/components/Menu.js:94:86)
    at TypeaheadMenu (webpack-internal:///../node_modules/react-bootstrap-typeahead/es/components/TypeaheadMenu.js:51:24)
    at InnerPopper (webpack-internal:///../node_modules/react-popper/lib/esm/Popper.js:48:35)
    at Popper (webpack-internal:///../node_modules/react-popper/lib/esm/Popper.js:212:31)
    at Overlay (webpack-internal:///../node_modules/react-bootstrap-typeahead/es/components/Overlay.js:115:24)
    at div
    at RootClose (webpack-internal:///../node_modules/react-bootstrap-typeahead/es/components/Typeahead.js:142:23)
    at TypeaheadManager (webpack-internal:///../node_modules/react-bootstrap-typeahead/es/core/TypeaheadManager.js:27:24)
    at Typeahead (webpack-internal:///../node_modules/react-bootstrap-typeahead/es/core/Typeahead.js:304:86)
    at TypeaheadComponent (webpack-internal:///../node_modules/react-bootstrap-typeahead/es/components/Typeahead.js:163:86)
    at eval (webpack-internal:///../node_modules/react-bootstrap-typeahead/es/behaviors/async.js:178:164)
    at Typeahead (webpack-internal:///./features/Typeahead/Typeahead.tsx:48:22)
    at div
    at div
    at form
    at div
    at div
    at SearchForm (webpack-internal:///./features/SearchForm/SearchForm.tsx:75:75)
    at div
    at div
    at Landing
```
My Typeahead wrapper component just does this:
```
return (
    <AsyncTypeahead
      filterBy={filterBy}
      id={`${name}-typeahead`}
      isLoading={isLoading}
      minLength={1}
      onSearch={getSuggestions}
      options={suggestions}
      placeholder={placeholder}
      promptText={promptText}
      searchText={searchText}
      emptyLabel={emptyLabel}
      labelKey={render}
      onChange={onSelect}
      onInputChange={onInputChange}
      isInvalid={isInvalid}
    >
      {({ onClear: onTypeaheadClear, selected }) => (
        <div className="rbt-aux">
          {selected && selected.length >= 1 && (
            <ClearButton
              onClick={async e => {
                await onClear(e);
                await onTypeaheadClear(e);
              }}
            />
          )}
        </div>
      )}
    </AsyncTypeahead>
  );
```

Last but not least, this issue seems to be highly related to https://github.com/facebook/react/issues/11538

Thank you in advance and regards

**Comment by ericgio** [comment]
Thanks for the report @javierguzman! This does seem to be related to the React issue you mentioned. Based on a quick reading of the thread, it sounds like [unwrapped strings are the root of the problem](https://github.com/facebook/react/issues/11538#issuecomment-390386520), since React can't properly keep track of them. It makes sense that the error is originating in the `Highlighter` component, since that component modifies and returns unwrapped strings.

I think the solution is probably simple (wrapping the string with a `span`), but I could use your help creating a reproducible test case. Interestingly, I'm not able to trigger the error on the [Example page](http://ericgio.github.io/react-bootstrap-typeahead/).

**Comment by javierguzman** [comment]
Hello @ericgio ! Yes, that comment gives the root of the problem as well as the workaround. I have created a minimal code example copying and pasting:

https://codesandbox.io/s/react-bootstrap-typeahead-google-chrome-crash-7dk3c?file=/src/App.tsx

However, the same as with the example page, the error does not happen. 

I have also changed my html tag from `<html lang="en">` to `<html lang="en" translate="no">`, which presumably disables automatic translation, and it seems to work ok. I mean, I enter the page, right click and click on translate. After that, when I start typing it does not crash. I am wondering whether codesandbox or the example page has something on the top of the chain that prevents the error as with translate="no".

It is confusing that automatic translation throws an error and manual translation (right click) does not throw an error... 😢

**Comment by ericgio** [comment]
Thanks @javierguzman! It looks like the workaround of [adding `translate="no"`](https://stackoverflow.com/a/21853147/882638) to the `html` element should work, as will [adding `className="notranslate"`](https://stackoverflow.com/a/9629628/882638) to an individual element.

I would recommend disabling translation for this component entirely, since the translations won't work very well. The error is triggered when menu items are highlighted, and the highlights are demarcated by `mark` tags. This breaks up the word from Translate's perspective and leads to mistranslations since it tries to translate the substrings.

**Comment by javierguzman** [comment]
Hello @ericgio ! Thanks for the explanation. Indeed that makes sense because I remember the error coming from the highlight code. So far, the workaround is ok for me because I am just starting on my web app. However, I am wondering whether this could be fixed in the future with the trick they wrote in the React issue? Or is it not possible technically?

**Comment by ericgio** [comment]
I think the fix is relatively simple in theory; it most likely entails wrapping the highlighter string with a `span`. I'm not able to consistently reproduce the error, however, so I can't test that solution. It would be helpful if you or someone else could provide a consistent repro case.

Even if the error is fixed, however, I still don't think the typeahead works well with translation, since it breaks up the string. For example, notice how Google tries to translate the following:

![image](https://user-images.githubusercontent.com/2978513/151714026-920c2d55-6f8e-4c0c-a858-2d6c39140885.png)

If you want to use Translate with your app, I'd recommend omitting the `Highlighter` component from your menu, which would also get rid of the error. You can do that by either rendering a completely custom menu (using `renderMenu`) or just the item contents (using `renderMenuItemChildren`).

**Comment by javierguzman** [comment]
Thank you @ericgio for the clear explanation! Indeed, the scenario you have shown is a nasty one. Ideally, it would be great to have the ability to tell the translator something like "hey, do not translate this single word, it is kind of a a substring" or something like that. Or maybe, from my ignorant point of view, is there another way to implement the highlight to avoid this? 

In any case, if I am the end user the ideal scenario for me would be that if I search for California,  I would like to see, California translated, which it seems not possible due to the highlight that is why you recommend disabling it. 

I think for now this issue has enough information at least for me. For sure, I am going to leave the translate="no" option. In addition, I will think about disabling the highlight because for me is a nice feature though. I plan to play more with translation in future, so it would be ok for me to close this issue for now and I can always re-open when I start messing around again :smile:  I might open also an issue on the Google translator tracker if there is one as this is something related to how translators work in general I believe.

**Comment by ericgio** [comment]
> Ideally, it would be great to have the ability to tell the translator something like "hey, do not translate this single word, it is kind of a a substring" or something like that... [I]s there another way to implement the highlight to avoid this?

You can pass `"notranslate"`  as a classname to the `Highlight` component to tell the translator to ignore the highlighted section:

```jsx
<Highlighter highlightClassName="notranslate" search="for">
  California
</Highlighter>

// Outputs
Cali<mark class="notranslate">for</mark>nia
```
That should solve the substring issue, and may possibly address the original error you were seeing. Note that using `<html translate="no">` would turn off translation completely; you may want to try the low-level approach to see if that solves your problem, allowing you to retain translation on the rest of the page.

**Comment by javierguzman** [comment]
Thank you again @ericgio ! That would be a perfect solution for me. Interestingly, so far with the translate="no", it just disables the automatic translation. However, the user using Chrome can still right click and click on translate, this will not provoke a crash and will work ok. 

Anyway, as I mentioned previously, I think from my side this is pretty much solved. So thank you very much for all the help.
