### ISSUE TITLE
Menu closes on input select all with mouse

### ISSUE THREAD

**Issue by ggepenyan** [ericgio/react-bootstrap-typeahead#696]
### Version
5.2.1

### Steps to reproduce
1. open https://codesandbox.io/s/9jq9jyzmry.
2. write down few letters to see the **menu with results**.
3. select the written text with mouse
4. release the mouse outside of the input (the issue doesn't happen wen mouse is released inside the input).

### Expected Behavior
The menu with results should not close when you select the written text.

### Actual Behavior
The menu with results closes when you select the written text and release the mouse key outside of the input.

**Comment by ericgio** [comment]
Hi @ggepenyan, thanks for reporting this issue! I can reproduce the behavior you describe, though I'm not sure it should be classified as a bug. The typeahead is listening for click events that happen outside of its bounds via [`useRootClose`](https://react-bootstrap.github.io/react-overlays/api/useRootClose), which attaches listeners to the document. If the `mousedown` and `mouseup` events happen on different elements, the `click` event happens [on the nearest parent of both elements](https://eloquentjavascript.net/15_event.html#:~:text=After%20the%20%22mouseup,both%20those%20paragraphs.):

> After the "mouseup" event, a "click" event fires on the most specific node that contained both the press and the release of the button. For example, if I press down the mouse button on one paragraph and then move the pointer to another paragraph and release the button, the "click" event will happen on the element that contains both those paragraphs.

Notice that the behavior you describe doesn't happen if you release the mouse while hovering over the open menu, since that is also contained within the typeahead bounds and thus won't trigger the root close behavior. Given what I've described, I believe the behavior you're seeing is expected.
