### ISSUE TITLE
Custom "Not Found" render

### ISSUE THREAD

**Issue by mxmtsk** [ericgio/react-bootstrap-typeahead#70]
Hello,
using the package as a search, so I'm loading the options from a remote source while rendering. Because of that, the options are empty at first which results on the "No results found" label being shown when focused the first time.

I would appreciate a "renderNotFound" method so I could customize this label for my needs.
I could - for example - change it to that to achieve a better UX in my case.

Would you consider adding a render method for this? 

```javascript
        renderNotFound={() =>
          <div className="not-found">
            {self.state.search.length === 0 ?
              'type a few characters to start searching' : 'No results found'}
          </div>
        }
```

**Comment by ericgio** [comment]
This should already be possible using the `emptyLabel` [prop](https://github.com/ericgio/react-bootstrap-typeahead#props). Have you tried that?

**Comment by mxmtsk** [comment]
Ai, completely missed that! Thanks! Still, it would be cool to have custom render method like it's already possible with the options to have more control over the layout. would you consider merging if I make a PR?

**Comment by ericgio** [comment]
All that's needed is for `emptyLabel` to accept a node instead of just a string, so that should be simple enough. If you'd like to make the change, I'll merge it. Please be sure to update the docs as well. Thanks!

**Comment by aashiqahmed98** [comment]
How to generate a custom menu with all the functionalites as like the regular case incase of Empty 'No match found' case?

**Comment by mazulo** [comment]
Hi @ericgio first of all, thank you so much for this lib, it is saving a lot of time!

I have a quick question about the `emptyLabel`. I saw on the doc that now it accepts a node instead of just a string, which is really nice. I was trying to pass to it a component with a specific behavior, it renders but the behavior does not.

The idea is that when the filter doesn't find anything, instead of showing a "not found" string we would show a button to add a new record. I have this quick example (which is basically a fork of yours with some tweaks to demonstrate what I'm trying to achieve): https://codesandbox.io/s/rbt-combobox-example-forked-j8ytb?file=/src/index.js

To save you from the click, here's the code:

```js
import React from 'react';
import { Typeahead } from 'react-bootstrap-typeahead';
import ReactDOM from 'react-dom';

import options from './data';

import 'react-bootstrap-typeahead/css/Typeahead.css';
import './styles.css';

function filterBy(option, state) {
  if (state.selected.length) {
    return true;
  }
  return option.label.toLowerCase().indexOf(state.text.toLowerCase()) > -1;
}

const ToggleButton = ({ isOpen, onClick }) => (
  <button
    className="toggle-button"
    onClick={onClick}
    onMouseDown={(e) => {
      // Prevent input from losing focus.
      e.preventDefault();
    }}>
    {isOpen ? '▲' : '▼'}
  </button>
);

const onClick = () => {
  return console.log('Hello there');
};

const AddSkill = ({ onClick, children }) => {
    return(<button onClick={onClick}>{children}</button>);
  );
};

const TypeaheadExample = () => (
  <Typeahead
    filterBy={filterBy}
    id="toggle-example"
    options={options}
    placeholder="Choose a state..."
    emptyLabel={
      <AddSkill onClick={(e) => onClick()}>Suggest new skill</AddSkill>
    }>
    {({ isMenuShown, toggleMenu }) => (
      <ToggleButton isOpen={isMenuShown} onClick={(e) => toggleMenu()} />
    )}
  </Typeahead>
);

ReactDOM.render(<TypeaheadExample />, document.getElementById('root'));
```

The button renders well but when I click nothing happens (not even an error). Would you know if that approach doesn't work at all with `emptyLabel`?

**Comment by mazulo** [comment]
I found it! Here on http://ericgio.github.io/react-bootstrap-typeahead/#custom-selections I see the `allowNew` prop which would give me the ability to add a new record. Solved one issue but created another one :joy: but this is for a new issue.

Thanks!
