### ISSUE TITLE
Not getting record

### ISSUE THREAD

**Issue by arukumar** [ericgio/react-bootstrap-typeahead#71]
Hi,
we are not getting record when we enter whitespace and then correct one, record not fetched. Once it display Record not found, record not displayed. See the screen shot. Is there any way to handle this one.

![image](https://cloud.githubusercontent.com/assets/16730673/17995157/fbc589e4-6b7c-11e6-84d2-f6e79dd69f64.png)

**Comment by ericgio** [comment]
This is the expected behavior ([see the filtering callback here](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/src/utils/defaultFilterBy.js#L16)). It's a string match that doesn't trim whitespace, so those spaces will cause the input not to match any results. To get around this, you can use the `filterBy` prop to write your own filtering callback that will ignore this whitespace.
