### ISSUE TITLE
Async search occasionally misses last letters

### ISSUE THREAD

**Issue by mdickin** [ericgio/react-bootstrap-typeahead#742]
### Version

6.0.0 (reproduced on http://ericgio.github.io/react-bootstrap-typeahead/#asynchronous-searching)

Have also seen this happen with 5.2.1

### Steps to reproduce

This can be hard to reproduce, it seems to depend on typing speed.
Occasionally, typing in the box will lose the last character or two. For instance (see below screenshots), typing "John" will only issue a search request for "joh".

It feels like something to do with the `debounce` function, but from what I've seen in the code, that's configured correctly (`leading` and `trailing` arguments aren't specified, so they default to 'false' and 'true' respectively)

### Expected Behavior

The search will contain all typed in characters (after accounting for any input delay).

### Actual Behavior

Results contain a few accounts that don't match "john"
![image](https://user-images.githubusercontent.com/16612667/197834371-fdd714fa-c90b-4aa7-b485-54c5dee6e031.png)

**Network inspector**
Only one request was issued
![image](https://user-images.githubusercontent.com/16612667/197834418-59cc045d-9443-4f87-9173-097b3e170ade.png)

**Comment by rg-coder** [comment]
@ericgio Could you please help to fix this issue. Many thanks in advance.

**Comment by nighto** [comment]
I am facing similar issues. What seems to be happening is that the request for "joh" is fired before the request for "john", but the first one takes more time to be returned, and if the previous call is answered after the next call, it overwrites it.

**Comment by nighto** [comment]
![image](https://user-images.githubusercontent.com/397851/207832531-b12806d5-a35e-4002-94e7-500f27ca09b8.png)

Check this example, of what I am trying to fix right now. Seems to be exactly what you are facing. You can see that this request taking longer to respond was fired before, but the actual response is after the request called longer. So it would overwrite the call made after.

Of course the server not always takes this much long to answer, that's why you have it depending to typing speed.

**Comment by nighto** [comment]
In this example, I am copy pasting the first part "72SR029001" and then typing "@6.95" at the end. I am logging on console the queried value on the `onSearch` function, and then the function called on promise resolution (after the values are actually fetched from backend)

![image](https://user-images.githubusercontent.com/397851/207834668-e4c50a8e-c3f1-45a9-bc92-83f124423efd.png)

As you can see it is not on the correct order, because the less specific query takes longer to return.

My approach / workaround to fix it is, when running the function on promise resolution, compare it with the value that is actually on the search field (i.e. `typeaheadRef.current.inputNode.value`) and only proceeding if they are the same.

**Comment by stanleyume** [comment]
Another solution is to use [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) to cancel any previous pending requests whenever a new one is fired.

**Comment by giose86** [comment]
Hi @mdickin 
did you read this? https://github.com/ericgio/react-bootstrap-typeahead/blob/main/docs/Upgrading.md#asynctypeahead-rewritten-with-hooks

I fixed the same behavior as you are facing applying the useCallback hook as reported in the doc.

**Comment by mdickin** [comment]
@giose86 thanks for that, I think that works for me as well! Hopefully we can get the example in the docs updated accordingly
