### ISSUE TITLE
Localization - Possibilities

### ISSUE THREAD

**Issue by pkartikyan** [ericgio/react-bootstrap-typeahead#764]
Someone, please let me know is there are any possibilities to implement localization. 

Project Details:

React, 
Localization package: "react-intl"

**Comment by ericgio** [comment]
Hi, @pkartikyan for usage questions, please post on forums like StackOverflow since your question will remain open and potentially help others facing the same issue. Posting there also helps me keep the issues queue manageable and limited to bugs and feature requests. Thanks!

https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead
