### ISSUE TITLE
Use `react-virtualized` instead of pagination

### ISSUE THREAD

**Issue by ericgio** [ericgio/react-bootstrap-typeahead#82]
Pagination was an easy way to keep the component performant when lots of options were rendered. [`react-virtualized`](https://www.npmjs.com/package/react-virtualized) solves the same problem but allows for scrolling through all the options.

**Comment by ericgio** [comment]
Took a stab at incorporating `react-window` and it only kind of works. Because of how the individual items are virtualized and reused, some functionality like keydown events get lost.

**Comment by ericgio** [comment]
Closing, as this is probably not something that will be offered out of the box. It makes more sense for developers to implement this individually as an advanced feature.

**Comment by ericgio** [comment]
Windowing example now available using [`react-tiny-virtual-list`](https://www.npmjs.com/package/react-tiny-virtual-list):
> [https://codesandbox.io/s/4q1yjrzrn0](https://codesandbox.io/s/4q1yjrzrn0).

Note: requires v4.0.0-alpha.9 or greater.

**Comment by gonzaloarca** [comment]
I tried this demo and an exception is thrown when attempting to type some option that isn't in the list. The exception is Requested index 0 is outside of range 0..0. 

Any ideas for solving this?

Cheers!

**Comment by gonzaloarca** [comment]
So it turns out that the `activeIndex` field in the `renderMenu` state parameter is actually -1 if there's no results, and that breaks the react-tiny-virtual-list List's `scrollToIndex` prop, which requires a non-negative value. 

So if you catch that case, then the crash is solved. However, I'm still not sure how we can display a nice "No matches found"-like placeholder given this scenario.
