### ISSUE TITLE
Package failing in parcel bundler

### ISSUE THREAD

**Issue by gagdiez** [ericgio/react-bootstrap-typeahead#830]
### Version

6.3.1

### Steps to reproduce

Clone this repository: https://github.com/gagdiez/rbt-error-minimal

Then:
1. yarn
2. yarn start
3. open browser in the URL indicated by parcel
4. See error `TypeError: Cannot read properties of undefined (reading 'default')`

### Expected Behavior

No error should be shown

### Actual Behavior

Error appears: TypeError: Cannot read properties of undefined (reading 'default')`

**Comment by ericgio** [comment]
Hey @gagdiez thanks for the report! I believe this is an issue with Parcel, albeit a very strange one. It looks like [this line](https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/js/src/esmodule-helpers.js#L11) is calling `dest.hasOwnProperty(key)`. However, this package has a helper function named `hasOwnProperty`. So rather than calling the prototype function, Parcel is trying to invoke the util function from this library and failing because it passes the wrong arguments. So they probably should change how they call `hasOwnProperty` to something like `Object.prototype.hasOwnProperty.call(dest, key)`.
