### ISSUE TITLE
There is no required attribute

### ISSUE THREAD

**Issue by romanbr87** [ericgio/react-bootstrap-typeahead#834]
**Is your feature request related to a problem? Please describe.**
required attribute doesn't exits. It's impossible to use typehead in forms 

**Describe the solution you'd like**
Just to add option for required 

**How is this solution useful to others?**
I think this problem can't prevent many people using this element in React 

**Describe alternatives you've considered**
I've build my own datalist based on HTML datalist and React-Bootstrap

**Comment by ericgio** [comment]
Hey @romanbr87, thanks for the feature request. The short answer here is that it's not really feasible to have default HTML behavior for a required form element and that you should probably be validating manually.

The form element is an input, so it can't track selections. For the single-selection case, you could pass a `required` value to `inputProps`, which will be applied to the input. However, this won't distinguish between arbitrary text from a user and a true "selection". For the multi-selection case, the input element is cleared as selections are made, so that approach won't work.

My recommendation is to track the selection state and validate the typeahead manually upon form submission.
