### ISSUE TITLE
Let the value of the input be controlled

### ISSUE THREAD

**Issue by Alevale** [ericgio/react-bootstrap-typeahead#859]
**Is your feature request related to a problem? Please describe.**
Right now I'm manipulating the content of the input with some very obscure logic that relies on this stak overflow answer. https://stackoverflow.com/questions/66170215/update-input-text-in-react-bootstrap-typeahead-from-javascript-react
This shouldn't be the default fix, and something more stable and robust should be offered as a solution

**Describe the solution you'd like**
Pass the input value as a prop

**How is this solution useful to others?**
When dealing with scanners, or when needing to format the content to comply with some other solution it might be that you need some manipulation of the input for UI compliance

**Comment by ericgio** [comment]
Hi @Alevale. This is a long-standing feature request that is unlikely to be implemented. Please see #266 for full discussion. The short version is that there don't seem to be that many use cases for the feature and it would potentially add a significant amount of complexity and overhead for developers, since they would have to manage additional typeahead state externally.

https://github.com/ericgio/react-bootstrap-typeahead/issues/266
