### ISSUE TITLE
Datasource change.

### ISSUE THREAD

**Issue by ing-fco-rguez** [ericgio/react-bootstrap-typeahead#93]
Hi, first of all your component is amazing.

What I'm trying to do is change the options to be displayed on the run (depending on the user's input), is it possible?

P.S.: I'm new to React, been working with it for like 2 weeks, also I know the above might not be the best practice but is a needed operation in the context of the system.

Thank you very much in advance.

**Comment by ericgio** [comment]
I think what you're describing is using the typeahead in an asynchronous manner, so that when the user enters text, you perform a query based on that text. Does that sound right?

This is totally doable, but it requires you to set up the code for data fetching and handling yourself. The typeahead component is "dumb" and simply renders what you pass in. See https://github.com/ericgio/react-bootstrap-typeahead/issues/78 for a bit more info on what I mean.

**Comment by ing-fco-rguez** [comment]
Thanks, that's just what I needed. :)
